name: CI for prod

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    env:
      working-directory: purithm
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: make application.yml file
        working-directory: ${{ env.working-directory }}
        run: |
          cd ./src/main/resources
          echo "${{ secrets.PROD_ENV_FILE }}" > ./application-prod.yml

      - name: Build with Gradle Wrapper
        working-directory: ${{ env.working-directory }}
        run: |
          chmod +x gradlew
          ./gradlew clean build